stages:
  load_data:
    cmd: python src/load_data.py
    deps:
    - src/load_data.py
    outs:
    - data/external/a1_RestaurantReviews_HistoricDump.tsv
    - data/external/a2_RestaurantReviews_FreshDump.tsv
  preprocessing:
    cmd: python src/preprocessing.py
    deps:
    - src/preprocessing.py
    - data/external/a1_RestaurantReviews_HistoricDump.tsv
    outs:
    - data/processed/corpus.joblib
  training:
    cmd: python src/training.py --output reports/model_evaluation.json
    deps:
    - src/training.py
    - src/evaluation.py
    - data/external/a1_RestaurantReviews_HistoricDump.tsv
    - data/processed/corpus.joblib
    outs:
    - data/models/c1_BoW_Sentiment_Model.pkl
    - data/models/c2_Classifier_Sentiment_Model
    metrics:
    - reports/model_evaluation.json
  linting:
    cmd: pylint src